= Experimental terminal emulator

"Terminix" is an experimental terminal emulator.
This is a for-fun project and if you want a _good_ terminal emulator you should probably look elsewhere.
This one is basically unusable.

It uses the GNU Unifont and _only_ the Unifont at the moment, so if you don't like that font... well...

You can print Klingon, so that's cool.

== Dependencies

* http://www.x.org[Xlib]
* https://www.khronos.org/egl[EGL]
* https://www.khronos.org/opengles[OpenGL ES 2.0]
* http://unifoundry.com/unifont/index.html[GNU Unifont]

Terminix embeds the GNU Unifont directly into its executable.
In order to do so, download and extract the Unifont's source code and extract it into a directory titled "unifont" in the same directory as the Makefile.

== Bugs

More than you can count.

* It sets `TERM` to `vt100` despite not truly being compatible, as many escape codes are unavailable.
* Lots of things are hard-coded so I could just get this working.
* Its a huge kludge of TODO's and disorganized code.

But hey, ViM works now.

== Special Thanks

Special thanks to Paul Flo Williams, who's article on DEC-compatible ANSI escape code parsers is the only reason this exists.
The flow chart is amazing!
If you look in `vtinterp.c`, you can see how directly I followed it (although this implementation is far from perfect).
Check it out: https://vt100.net/emu/dec_ansi_parser

I would've used https://github.com/haberman/vtparse[Josh Haberman's public domain implementation], linked to from the article, but most of the fun of this project has been hand-coding an interpreter so it would've been way less enjoyable.

== Copyright, License, and Warranty

Copyright (C) 2019 Megan Ruggiero. All rights reserved.

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

The binary that results from the build procedures described in this README will embed the GNU Unifont into the final executable.
The GNU Unifont is licensed under the GNU General Public License, whose terms will cover the final executable as a derivative product.
Please see the Unifont's license for more information.

NOTE: The GNU Unifont includes a "font embedding exception" that states that documents embedding the Unifont are not covered under the GNU GPL.
However, Terminix is software, not a document, and as such I do not believe it is covered under the exception.
I am not a lawyer.
Please contact the GNU Unifont developers or the GNU Project for clarification if necessary.