= Experimental terminal emulator

"Terminix" is an experimental terminal emulator.
This is a for-fun project and if you want a _good_ terminal emulator you should probably look elsewhere.
This one is basically unusable.

It uses the GNU Unifont and _only_ the Unifont at the moment.
Test calls demonstrated that the rendering can technically print Pikto but for some reason I am having trouble printing Klingon.
Note, though, that UTF-8 parsing is not yet implemented so programs can't print Unicode directly.

== Dependencies

Terminix requires the https://liballeg.org/[Allegro 5.x] series of game programming libraries.
I know: game libraries for a terminal emulator?
Well, it's the graphics APIs I work with the most so it's what I'm using for now.
If I don't abandon this then I'll use something a bit more sensible.

It also requires the http://unifoundry.com/unifont/index.html[GNU Unifont], which is built into a custom bitmap font by `buildfont.rb`.

== Build Instructions

Terminix embeds the GNU Unifont directly into its executable.
In order to do so, download and extract the Unifont's source code and extract it into a directory titled "unifont" in the same directory as this README.
Then, run `./buildfont.rb` to compile the Unifont into `src/unifont.c`.

NOTE: Originally I used TrueType fonts, but found Allegro's routines to be fairly weak for glyph stretching and things like that while trying to implement double-height text.
I then switched to bitmap fonts which saved a significant amount of disk space and fixed the issues I was having with glyph stretching.
Now, I've switched to embedded binary data.
Since this data is uncompressed, this method sacrificed disk space (the compiled data is about the size of the TrueType fonts) but significantly improved startup time.

Now, simply run `./build.sh` to compile the program.
To execute the program, run `./terminix`.

== Bugs

More than you can count.

* It sets `TERM` to `vt100` despite not truly being compatible, as many escape codes are unavailable.
* Lots of things are hard-coded so I could just get this working.
* Its a huge kludge of TODO's and disorganized code.

But hey, ViM works now.

== Special Thanks

Special thanks to Paul Flo Williams, who's article on DEC-compatible ANSI escape code parsers is the only reason this exists.
The flow chart is amazing!
If you look in `vtinterp.c`, you can see how directly I followed it (although this implementation is far from perfect).
Check it out: https://vt100.net/emu/dec_ansi_parser

I would've used https://github.com/haberman/vtparse[Josh Haberman's public domain implementation], linked to from the article, but most of the fun of this project has been hand-coding an interpreter so it would've been way less enjoyable.

== Copyright, License, and Warranty

Copyright (C) 2019 Megan Ruggiero. All rights reserved.

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

WARNING: The following details are based on my best effort interpretation of the license terms for the GNU Unifont.
I am not a lawyer, so I don't know if this is a correct interpretation of the Unifont's license.
Please seek professional legal advice in order to make sure you properly comply with Unifont's license terms.
Eventually I will contact the Free Software Foundation, GNU Project, and/or GNU Unifont developers to make sure I am properly interpreting this.

The resulting binary will include a compiled version of the GNU Unifont.
_I think_ the resulting binary will be covered by the GNU General Public License version 2 or later, with the Unifont's embedding exception.
The exact license text for the Unifont can be found in its distribution, and _I think_ it must be distributed with all copies of the resulting binary.

I am not including a copy of the license here in case you use a version of the GNU Unifont with slightly (or extremely) different license terms.
Please see the Unifont distribution you download to build Terminix for its license terms.